### ISSUE TITLE
ERROR: epoll_wait: Interrupted system call

### ISSUE THREAD

**Issue by etam** [travisghansen/fanout#19]
ERROR: epoll_wait: Interrupted system call

This happens to, I think, suspending/resuming my machine.

The solution: http://stackoverflow.com/a/6870391/952263

**Comment by travisghansen** [comment]
Just so I'm clear this only shows up when a suspend/resume action occurs on your machine?

**Comment by etam** [comment]
Yep. That's exactly the cause.

**Comment by travisghansen** [comment]
@etam can you try applying this and let me know how it goes?

diff --git a/fanout.c b/fanout.c
index 6688638..bf9fbbe 100644
--- a/fanout.c
+++ b/fanout.c
@@ -503,8 +503,12 @@ xit\n");
 
         fanout_debug (3, "server waiting for new activity\n");
 
-        if ((nevents = epoll_wait (epollfd, events, max_events, -1)) == -1)
+        if ((nevents = epoll_wait (epollfd, events, max_events, -1)) == -1) {
+            if (errno == EINTR) {
+                continue;
+            }
             fanout_error ("epoll_wait");
+        }
 
         if (nevents == 0) {
             continue;

**Comment by etam** [comment]
It goes fine.
